include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    always_declare_return_types: true
    directives_ordering: true
    sort_pub_dependencies: true